In [1]:
import pandas as pd
import numpy as np
from numpy import genfromtxt
import scipy as sc
from scipy.signal import medfilt
from scipy.signal import find_peaks
from scipy.signal import find_peaks_cwt
import sys
import numpy

In [5]:
# Median Filter on V1 Lead 

df = pd.read_csv("C:\\github\\Deep-Learning-for-Heartbeat-classification\\mitbih_database\\205.csv")
# print(df)
data= df[df.columns[2]].to_numpy()
# print(data)
num_600 = medfilt(data, 601)
print(num_600)

num_200 = medfilt(num_600,201)
print(num_200)

num_28 = medfilt(num_200, 27)
print(num_28)

[868. 871. 873. ... 906. 903. 903.]
[868. 871. 873. ... 906. 903. 903.]
[868. 871. 873. ... 906. 903. 903.]
